### ISSUE TITLE
howdoi for research 

### ISSUE THREAD

**Issue by HajerMahjoub** [MLH-Fellowship/howdoi#29]
a plugin that capable to answer howdoi  with --research option the answer will be linked to https://arxiv.org/ research paper that it's related to the question asked maybe using the arxiv  API https://arxiv.org/help/api or a simple similarity between the question and the title of the paper is how the plugin work 
I've worked on a similar idea before so can help if you would join this issue

**Comment by HajerMahjoub** [comment]
@csr have time to read the documentation and will send you similar code i've done 
 https://arxiv.org/help/api/user-manual

**Comment by csr** [comment]
Thank you!

**Comment by HajerMahjoub** [comment]
url = "http://export.arxiv.org/api/query?search_query=all:electron&start=0&max_results=10"
r = requests.get(url, allow_redirects=True)
if r.status_code == 200:
    print('Success!')
    r.encoding = 'utf-8'
    print(r.text)

elif r.status_code == 404:
    print('Not Found.')

**Comment by csr** [comment]
Hey! I've just pushed some code on the [csr-29-research](https://github.com/MLH-Fellowship/howdoi/tree/csr-29-research) branch.

This is an example response we get:

```
{'arxiv_id': '1207.3006v1', 'title': 'Excitation Suppression Due to Interactions Between Microwave-Dressed Rydberg Atoms', 'summary': '  Atom-atom interactions within a small volume were investigated through the\nexcitation of ultracold Rb atoms. The application of microwaves enhances these\ninteractions, causing the suppression of Rydberg state excitation. The\nsuppression of Rydberg atom excitation was both qualitatively observed and\nquantitatively analyzed using a universal scaling law, giving a measure of the\natom-atom interaction strength in agreement with theoretical prediction.\n', 'authors': [{'name': 'E. Brekke', 'affiliation': []}, {'name': 'J. O. Day', 'affiliation': []}, {'name': 'T. G. Walker', 'affiliation': []}], 'arxiv_url': 'http://arxiv.org/abs/1207.3006v1', 'pdf_url': 'http://arxiv.org/pdf/1207.3006v1', 'primary_category': 'physics.atom-ph', 'categories': ['physics.atom-ph'], 'comment': None, 'doi': '10.1103/PhysRevA.86.033406', 'journal_ref': None}
```

Feel free to review the code. Let's talk next steps later today :)

**Comment by HajerMahjoub** [comment]
@csr i reviewed and tested the result is well structured yes we can discuss the next step later today :100:

**Comment by csr** [comment]
As for next steps, I think we can turn this into a plugin when we're done with the plugins architecture.

**Comment by HajerMahjoub** [comment]
@csr that will be perfect I can work on that  and I will also turn wikihow to plugin

**Comment by csr** [comment]
Great!
