### ISSUE TITLE
Share draft of flows in this issue

### ISSUE THREAD

**Issue by FawziyahAlebiosu** [MLH-Fellowship/howdoi#3]
@diarreola @FawziyahAlebiosu

**Comment by FawziyahAlebiosu** [comment]
![image](https://user-images.githubusercontent.com/20774412/84200165-480d9780-aa74-11ea-95a3-1de40ce3578a.png)
the first option:
 - user enters command through bar at the top, then the suggestion/answer shows up as a banner on the side

the second option:
- user enters a word(maybe it will say howdoi print) then they highlight it, and go to the bar at the top and type howdoi, then they presse enter. This will give them a list of possible options as a dropdown selection

the third option:
- they write howdoi print right in their code, then just like how intellisense works, it will suggest the answer, then they press enter. This will give them the answer right in the ide

**Comment by FawziyahAlebiosu** [comment]
fourth option:
- type print in command line(without howdoi), highlight it, and go to the pallette. It will automatically apply the answer to your code/replace it with the answer

**Comment by FawziyahAlebiosu** [comment]
fifth option:
- enter howdoi print, no highlight, then go to command pallette, and run the command howdoi. It will go through and automatically apply/replace with answer.
- this would allow for multiple howdois!

**Comment by diarreola** [comment]
first option:
<img width="1092" alt="option1" src="https://user-images.githubusercontent.com/35948232/84207828-20640280-aa67-11ea-929f-f11405fc3270.png">

**Comment by diarreola** [comment]
second option: *bold = highlighted text
<img width="984" alt="option2" src="https://user-images.githubusercontent.com/35948232/84208492-b2b8d600-aa68-11ea-8aea-87d22b7b10f5.png">

**Comment by diarreola** [comment]
third option: 
<img width="1059" alt="option3" src="https://user-images.githubusercontent.com/35948232/84209329-c2d1b500-aa6a-11ea-9128-02984444cd06.png">

**Comment by diarreola** [comment]
fourth option:  *bold = highlighted text
<img width="1001" alt="option4" src="https://user-images.githubusercontent.com/35948232/84209367-d2e99480-aa6a-11ea-9073-8ff02bf8b227.png">

**Comment by diarreola** [comment]
fifth option:

<img width="1013" alt="option5" src="https://user-images.githubusercontent.com/35948232/84209420-f44a8080-aa6a-11ea-881c-51c9f6ed45f8.png">

**Comment by diarreola** [comment]
sixth option: 
Instead of replacing the `howdy print python` line, the answer is inserted below it.
<img width="1066" alt="option6" src="https://user-images.githubusercontent.com/35948232/84209479-16dc9980-aa6b-11ea-8e69-e3aa0d85cdf6.png">

**Comment by FawziyahAlebiosu** [comment]
These look great Diana!!!
