### ISSUE TITLE
publish extension on vs-code market place

### ISSUE THREAD

**Issue by diarreola** [MLH-Fellowship/howdoi#32]
- create marketplace icon
- figure out name for extension

**Comment by diarreola** [comment]
@gleitz Is there a certain icon you have in mind for the howdoi vs-code extension?

**Comment by gleitz** [comment]
I'll reach out to my friend who is a designer - he can make us an icon :)

https://benbronstein.com/

**Comment by gleitz** [comment]
I'll also reach out to the old VSCode extension maintainer to see if they can remove what they have from the store. Then we can simply call it `howdoi`

**Comment by gleitz** [comment]
He was actually very nice. Already removed his extension so there is no longer anything in the store called howdoi.

Do you have any specs for the icon? I figure it will be square and we'll make 1000px versions also smaller.

**Comment by diarreola** [comment]
On the VS code [publishing doc](https://code.visualstudio.com/api/working-with-extensions/publishing-extension) it states that the icon must be a squared 128px PNG and not an SVG.

**Comment by diarreola** [comment]
@gleitz it's live! https://marketplace.visualstudio.com/items?itemName=howdoi-org.howdoi

**Comment by gleitz** [comment]
Five starz!

**Comment by diarreola** [comment]
there is a slight lag when running the command 😭
