### ISSUE TITLE
basic eslint file for javascript/typescript

### ISSUE THREAD

**Issue by diarreola** [MLH-Fellowship/howdoi#37]

**Comment by diarreola** [comment]
add ESLint file for plugin. the extension file already has it.

**Comment by gleitz** [comment]
Yes, that's it! Here are some "rules" flags I've used for other projects to require 2-space indents and 120 line length. VSCode should be able to run eslint for you (might need to enable it) and pull in the .eslintrc.json file.

```
    "max-len": [
      "error",
      {
        "code": 120
      }
    ],
    "indent": [
      "error",
      2,
      {
        "SwitchCase": 1,
        "flatTernaryExpressions": false,
        "ignoreComments": false
      }
    ],
```

**Comment by diarreola** [comment]
Add a space after variable and before typescript types (foo:HowdoiResult -> foo: HowdoiResult)
Remove all semicolons (It's weird, I know, but they aren't necessary
in Typescript. I also changed the .eslintrc file to show errors if
semicolons are included)
Prefer using ' everywhere rather than " (added eslint rule)
Make sure that there is always a space after a comma (added eslint
rule)
Fix indentation according to lint suggestions
Some of these changes are personal preference, but by attaching an
associated eslint rule and requiring that linting pass before a PR can
be accepted, you can keep the codebase readable and uniform.

**Comment by diarreola** [comment]
@gleitz right now I'm running eslint via npm. Did you want me to add these linting rules to your Travis CI?

**Comment by gleitz** [comment]
If possible that would be great!
