### ISSUE TITLE
Be able to see text that user has highlighted

### ISSUE THREAD

**Issue by FawziyahAlebiosu** [MLH-Fellowship/howdoi#4]
this should also extend to:
- commented AND uncommented text
   - this is so that even beginners to programming who don't know to comment their code can utilize this extension.

**Comment by FawziyahAlebiosu** [comment]
update on this :
I have been able to get it to recognize comments, and remove it before sending the query. However, it currently only works for python comments, so I'll modify it to include comments in other languages too. By removing any non letter that the text starts with.

**Comment by diarreola** [comment]
This currently works for uncommented text within the code editor

**Comment by diarreola** [comment]
wondering if this should also extend to a user typing in `howdoi  etc etc` and the various in which this is a comment
