### ISSUE TITLE
enable json for plugin

### ISSUE THREAD

**Issue by diarreola** [MLH-Fellowship/howdoi#47]
utilize json flag to retrieve query data in both plugin and extension

**Comment by diarreola** [comment]
@gleitz When trying to execute `python -m howdoi.howdoi print stack track trace -n3 -j` command to enable json I receive an error. For setup I cloned your repo, installed the requirement.txt file, and ran the common `pip install . ` to install any other python packages. I am running this command from the root directory and I receive this error:
<img width="1054" alt="Screen Shot 2020-06-30 at 11 58 42 AM" src="https://user-images.githubusercontent.com/35948232/86166190-39d9f680-bac9-11ea-96ca-7812b63277eb.png">

**Comment by gleitz** [comment]
Please pull and try again https://github.com/gleitz/howdoi/commit/ec6c40c71ae0bd6575b6f171dcb53df633caaafd

If you're still getting an error, then please update to Python 3 as we're probably dropping support for 2.7 soon...
