### ISSUE TITLE
Integrate Github Actions CI

### ISSUE THREAD

**Issue by diarreola** [MLH-Fellowship/howdoi#48]

**Comment by diarreola** [comment]
@gleitz I just added a `.travis.yml` file into the extension folder for Travis CI. Although, I just found out that there can only be one `.travis.yml` file. In that case, is it ok to add the code in my `.travis.yml` file into howdoi's `.travis.yml` file? Upon further research, I found that GitHub actions has the ability to have more than one `yml` file, however that would mean migrating from Travis CI to GitHub actions. In addition, another way to go about this issue can be to place my extension project into a submodule. Let me know which one you are on board for.

**Comment by gleitz** [comment]
Perhaps we would want to switch to github actions and away from Travis? 

Some other fellows are working on flows that use actions so it seems like a good move to me.
