### ISSUE TITLE
Be able to show at least ONE suggestion inside the command pallette as a drop down menu

### ISSUE THREAD

**Issue by FawziyahAlebiosu** [MLH-Fellowship/howdoi#7]
if feeling ambitious, we can do 3 suggestions

**Comment by diarreola** [comment]
Now able to see the three possible suggestions although only the link portion shows. Need to update this with the actual suggestions.
<img width="749" alt="Screen Shot 2020-06-11 at 11 46 58 AM" src="https://user-images.githubusercontent.com/35948232/84427143-43aebf00-abd9-11ea-995c-db3548463b6a.png">

**Comment by diarreola** [comment]
Now able to see suggestions
<img width="673" alt="Screen Shot 2020-06-11 at 1 24 20 PM" src="https://user-images.githubusercontent.com/35948232/84435553-ddc93400-abe6-11ea-819d-b14d85cbf408.png">
