### ISSUE TITLE
Be able to output the link as a comment AND the result of the query inside the code editor below the line that has the search query

### ISSUE THREAD

**Issue by FawziyahAlebiosu** [MLH-Fellowship/howdoi#9]

**Comment by diarreola** [comment]
commenting will differ for each programming language, which might make this a bit more difficult. Although, VScode api might have a solution for this :)

**Comment by diarreola** [comment]
currently: 
<img width="847" alt="Screen Shot 2020-06-11 at 11 57 59 AM" src="https://user-images.githubusercontent.com/35948232/84428126-cd12c100-abda-11ea-9bb8-476ad93336fc.png">

**Comment by diarreola** [comment]
This issue is similar to [issue 10](https://github.com/MLH-Fellowship/howdoi/issues/10), where I need to make a line a comment.
